version: "3.8"
services:
    localdns:
        container_name: localdns
        network_mode: bridge        #use default bridge network instead of implicit docker-compose custom network
        image: jpillora/dnsmasq
        restart: always
        ports:
            - "53:53/udp"
            - "5380:8080"
        environment:
            MAPPED_HOSTS: "/etc/docker-dns/hosts.json"
            HTTP_USER: "user"
            HTTP_PASS: "user"
        volumes:
            - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    nginx:
        container_name: nginx
        image: nginx:alpine
        #network_mode: bridge        #use default bridge network instead of implicit docker-compose custom network
        restart: always
        volumes:
            - ./nginx/certs:/etc/nginx/certs
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
    demo.docker:               #postfix .docker to resolve in internal network
        container_name: demo
        image: nginxdemos/hello
        restart: always

networks:
    default:
        external:
            name: dockerdev